-- Add alias column to participants table for smart name display
-- The alias will be auto-generated by the application when new participants register
ALTER TABLE participants ADD COLUMN IF NOT EXISTS alias VARCHAR(100);
